---
title: "Topic 3: Problems, mishaps & blameless postmortems"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 3 Materials

-   Week 3 [Slides](https://docs.google.com/presentation/d/e/2PACX-1vQJ1lFyIwSjhAiWfog3Hsr_4BaIxZyz7ogl8oh2hKn_sohm_GlN1S49AynYJmjKIkiE4StFYQiA-DI5/pub?start=false&loop=false&delayms=3000)

## Week 3 Goals:

-   Address questions on Solution Design
-   Share a "Weekly Win"
-   Peer review & sharing: Solution Design
-   "State of your data" blitz
-   Introduction to the blameless postmortem
-   Clarifying the problem / gap that **your project** addresses

## Today's timeline:

-   **1:00 - 1:30** - Reminders, questions & share some wins / ideas
-   **1:30 - 2:00** - Solution design group sharing & questions / gaps clarified
-   *2:00 - 2:10 - Break*
-   **2:10 - 2:25** - Group time (flash talk prep)
-   **2:25 - 3:00** - Flash talks (solution design overview)
-   **3:00 - 3:20** - "State of your data" blitz
-   *3:20 - 3:30 - Break*
-   **3:30 - 4:00** - Mishaps & blameless postmortems (mini-lecture / discussion)
-   **4:00 - 4:15** - What's your problem? (research storytelling mini-lecture)
-   **4:15 - 4:45** - From background to specific problem / gap - directed work
-   *4:45 - 5:00 - Wrap up & group time*

## What you should do before next week: 

-   Draft **Problem Statement and Objectives** section of Design & Implementation Plan

-   Continue work on Solution Design section (full draft expected, or placeholders where gaps exist)

-   Next week be prepared to present:

    -   A 3 minute flash talk on Timeline & Milestones (2 presenters minimum)

    -   A 3 - 4 minute presentation (2 presenters minimum) with the following:

        -   Cover slide (1 slide)

        -   Background (1 - 2 slides)

        -   Problem / gap (1 slide)

        -   Objectives (1 slide)
