---
title: "Week 1: Hello, (Capstone) world!"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 1 Materials

- Week 1 [Slides](https://docs.google.com/presentation/d/e/2PACX-1vR2FTOKqfY9MLh40qLPA77ZCQ6Yx_Xxm_DPZSpfYaixwA0CRq_bmvy3qZtz3AQMoa6WA88StOE8trb6/pub?start=false&loop=false&delayms=3000)

## Week 1 Goals:

- EDS 411AB course introduction
  - What are we doing here?
  - What is the time expectation? 
  - How will I be evaluated?
  - How do we get help?
- Tell us about your project! 2-minute flash talks 
- Write a short paragraph on your project for the Bren website
- Finance team visit - how to use your Capstone funds
- Decide on a project alias
- Define team roles

### 1:00pm - 1:30pm: EDS 411AB Course Intro

- Who's presenting? Allison
- Where: On Zoom! 
- When: 1:00 pm PST - 1:30 PST

### 1:30pm - 2:15pm: Project Flash Talks

Spend 15 minutes creating then practicing a 2 to 3 minute, 3 slide presentation on your project. The 3 slides should be (1) Background, (2) Project motivation (or problem / knowledge gap), (3) Project objective(s). Your group can decide how you break up the presentation - 2 presenters minimum. 

**Break: 2:15pm - 2:30pm PST**

### 2:30pm - 3:00pm: Write a summary for the Bren website

Each MEDS Capstone project will be featured on the Bren website. Spend ~10 minutes browsing some [MESM project summaries](https://bren.ucsb.edu/projects) to get an idea of what is expected. Then, start drafting your paragraph for the website in the shared document.

### Finance - using your group money (3:00pm - 3:30pm)

Members of the Bren finance team will join via Zoom to go over important information about using your Capstone budget & how to use it. 

**Break: 3:30pm - 3:45pm**

### 3:45pm - 4:00pm: Team alias! 

Your team alias - a short, memorable abbreviated name for your project - serves multiple professional purposes, including: 

- The directory name on Taylor
- Your group's email prefix 
- Use in MEDS Capstone communication with faculty and staff

Spend 15 minutes brainstorming group aliases. Keep in mind that this will likely be part of a file path, so using good practices for naming things is in your best interest. Some examples of team aliases from previous Bren MESM projects are: 

- **nadatrace** (evaluated opportunities for Nada Groceries to minimize waste)
- **worthwhale** (economic valuation of whale watching & marine planning in Dominica)
- **maricultura** (assessed Brazil's aquaculture potential)
- **justhealth** (investigated relationships between air quality and diabetes risk in California)

Once you have decided on your team alias, send it to Brad & Kat so they can set up your Taylor directory and group email address. 

### 4:00 - 5:00pm - Define team roles and report back

All teams are required to have a project manager (PM) and communication manager (CM). Other roles should be decided based on project-specific needs and expectations. Discuss with your team - in addition to the PM and CM, what do you think are the most important roles for the success of the project? 

Add your proposed roles to [this shared doc](https://docs.google.com/spreadsheets/d/19iI1BGMthN6ccFWxkMGPeT8aWXAsnonYmXkO6K9CfMM/edit#gid=0) by the end of the day. You should discuss the proposed roles with your faculty advisor, and make updates to the Googlesheet to finalize your project roles by Friday, January 11th.  

## What you should do before next week: 

- All members should read through the [MEDS Capstone Guidelines](https://bren.ucsb.edu/media/3557/download)
- Prepare a first draft of the Team Management Plan section of your Design & Implementation Plan (and feel free to work on other sections!)
- Let Brad & Kat know your team alias ASAP (so they can create your Taylor directory & email)
- Make sure your project roles are updated on the [shared Googlesheet](https://docs.google.com/spreadsheets/d/19iI1BGMthN6ccFWxkMGPeT8aWXAsnonYmXkO6K9CfMM/edit#gid=0)


